### ISSUE TITLE
Discussion about the Building Infrastructure class Diagrams

### ISSUE THREAD

**Issue by aolite** [HIT2GAP-EU-PROJECT/HIT2GAPOnt#24]
Open discussion about the Building Infrastructure class Diagrams

**Comment by aolite** [comment]
From @ycardinale: 
Regarding Section 13.1.2: Geographic Information (Hemispheres, Climate types, Orientation), there some concepts explicitly considered in the ontology proposed by Richard (Onto_H2G).

The ifc:SpatialStructuralElement concept hasOrientation, and ifc:Building isA ifc:SpatialStructuralElement. We can integrate Hemispheres and Climate types information related to
ifc:SpatialStructuralElement.

Also, in Onto_H2G, it is proposed a classification of concepts related to energy equipments (Power System) into five categories named IGOEE: Identification, Geographical, Operational, Economical, and Ecological.

We can complete the Geographical concepts with (Hemispheres, Climate types, Orientation. Currently only concepts related to Mobility (Location and time) are considered.

In Minerva Ontology there is a GeographicModel, described as "Geographic representation of the entities: This package is focused on linking the SSN module with geographic contextualisation of the information. This ontology will support in the future the geospatial reasoning over the elements of the domain-specific ontologies."

I think that we can extend this Minerva:GeographicModel with this information.

However, in the APIs, the Geographic information is attached to the building description, while in Onto_H2G is related partially to ifc:SpatialStructuralElement and to the energy equipments. In Minerva Model ssn:System and ssn:FeatureofInterest inherit from geo_Feature that in turns hasGeometry (GML, WKT).

Thus, we should see together this subject to decide if it is necessary to create other concepts and relations in Onto_H2G or Minerva Geographic Model. I prefer the first option: Adjust ifc:SpatialStructuralElement.

Section 13.1.3 Energy categories. This information was taken from ONTO-MG. Then, it is well considered.

Section 13.1.4 Systems. This information was taken from IFC and Haystack. However, there are concepts (Monitoring, Wearable) and relations described in the document D.2.7 that are not described in the document of the Onto_H2G.
We have to take into account these concepts and relations when we work on Building and sensor modeling.

Section 13.1.5 Measures This information is from MONDAS?

Section 13.1.6 Occupancy. Some of this information is considered on the USER-Simulation Module. However there is other information (such as Distant to a point, Level of Knowledge) that we should discuss how they will be modeled.

I think that a meeting to discuss all these aspects is necessary.

**Comment by ycardinale** [comment]
I'm reviewing the link about this aspect and I'will let you know my suggestions.

When can we have a meeting to discuss these aspects?
