### ISSUE TITLE
Prepare Occupant class diagram

### ISSUE THREAD

**Issue by aolite** [HIT2GAP-EU-PROJECT/HIT2GAPOnt#3]
Convert current Occupant class diagram Graph into a HTML based diagram using plantuml.

**Comment by aolite** [comment]
![user-ontov2](https://cloud.githubusercontent.com/assets/4601466/24913883/de074992-1ed2-11e7-8483-01b6967c8909.png)

**Comment by aolite** [comment]
Generation of the initial version of the User comfort plant uml and documentation. Plase revise it and write here your approval or dissaproval (indicating the improvement points and contributions). 

https://hit2gap-eu-project.github.io/HIT2GAPOnt/

**Comment by ycardinale** [comment]
Thank you Aitor!
I will update the DataModel_ClassDiagram. I did some improvements.

**Comment by aolite** [comment]
@ycardinale please make the changes directly over the new diagrams due to I have also made changes...

**Comment by aolite** [comment]
I have considered the newer Class Diagram in the performed changes over occupancy (weekend mail). If there is some changes offline, plase paste here the newer model.

**Comment by aolite** [comment]
Please, the dicussion continues on the issue #23
