### ISSUE TITLE
Dead links to Building Infrastructure Ontology and User Behaviour Ontology in README.md

### ISSUE THREAD

**Issue by oscarechobravo** [HIT2GAP-EU-PROJECT/HIT2GAPOnt#32]
There seems to be dead links to Building Infrastructure Ontology and User Behaviour Ontology in README.md. 

We're starting a new project on building contextual data into commercial energy/building analytics and wanted to check out the platform and the ontologies you used.

**Comment by pbourreau** [comment]
Hi,
I just fixed this. 
We are currently refactoring the ontology and the platform, and we hope we can deliver a new version next summer. If you have any comment or suggestion regarding the current version let us know, se we can consider it in our rework.
Thanks!
