### ISSUE TITLE
Meeting with Richard to update the semantic model status

### ISSUE THREAD

**Issue by aolite** [HIT2GAP-EU-PROJECT/HIT2GAPOnt#6]
Meeting with Richard to update the status of the model definition

**Comment by ycardinale** [comment]
From the meeting with Richard these are his comments:
1. He thinks that it is not necessary to have NonPhysicalNeeds and PhysicalNeeds, only  HIT2GAP:Needs will be enough (and the other subclasses). We searched in obXLM for more information about NonPhysical and PhysicalNeeds but there is not too much. If you have more information about the necessity of having these two concepts, then we can justify them.

2.   What is the idea of the concept HIT2GAP:Inaction. I suppose that, it is the fact when it is nothing to do. Now the question is: Do we need to register this information? Again, in obXML there is no much information about it.

3. He thinks that HIT2GAP:Season isA Time:DateTimeInterval. What do you think? Actually, if that is the case, the Time:DayOfWeek should be also a DateTimeInterval, don't you think? 

4.  We think that HIT2GAP:OccupantAttitude should be related with Behavior Model. May be HIT2GAP:OccupantAttitude isA Behavior Model ?

**Comment by aolite** [comment]
Great!!! Continuing with the same numbering: 

1. From obXML the definition for both concepts are: 
> Physical needs include: (i) thermal comfort or satisfaction with the thermal environment, which is a combination of indoor air temperature and humidity, surrounding surface temperatures, indoor air velocity, activity level, incident radiation and clothing level of the occupant [88,107,150,151]; (ii) visual comfort such as not being subjected to glare, excessive contrast or unacceptable levels of brightness; (iii) acoustic comfort, with the level of background  noise within an acceptable range; (iv) indoor environmental health, meaning good IAQ or humidity. Non-physical needs include factors such as the need for privacy or the need to maintain outside views. 

From my point of view, we could maintain "Needs" only as a concept. No problem. 

2. The idea of "inaction" is to register the no action of the occupants when a comfort anomaly or even discomfort occurs. This inaction could be derived from some policies or restriction to the occupants. It could be interesting those states but only when anomalies or discomfort occurs.

3. According to the W3C specification, 

> The class :DateTimeInterval is a subclass of :ProperInterval, being an interval whose boundaries fall on the limits of a date-time description with truncated precision.

That means, this definition includes specific date times for the interval. 

In the case of time:DayOfWeek, the documentation of the W3C categorise it separatelly. Therefore, I propose to maintain it as it is or almost define a upper class denoted as HIT2GAP:TimeInterval

4. Why maintain both??? Can we maintain only one?? If not, OK to the proposal.

**Comment by ycardinale** [comment]
Thank you Aitor. More comments with same numbering:
1. I think that to avoid ambiguity (some Non-physical needs can be related to physical needs or can be difficult to separate them), we can keep only "Needs" and the subclasses Preferences, Privacy, Thermal, Acoustic, IAQ, Visual. Even so, we are considering all propositions of obXML.

2.  OK. Let's keep it.

3. For me the option of keep it as it is sounds better. We should wait for other opinions? 

4. You're right, I think that we can maint only one: OccupantBehavior Model or just Behavior Model?

**Comment by aolite** [comment]
1. OK. Let's maintain only the "Needs" class and the subclasses "OccupantPrefrences", "Privacy", "Thermal", "Acoustic", "IAQ" and "Visual". 
2. OK
3. OK
4. I propose "OccupantBehaviourModel"

I will create the corresponding issues.
