### ISSUE TITLE
Ensure D2.7 information coverage with the current version of the semantic model

### ISSUE THREAD

**Issue by aolite** [HIT2GAP-EU-PROJECT/HIT2GAPOnt#7]
Ensure that the APIs information and the categorised inforamtion on D2.7 (Annex 13) is covered in the semantic model.

**Comment by ycardinale** [comment]
I started with **Section 13.1.1 Building Information**
a) Concerning **Building Types**, I looked at ifc, Minerva, and Richard's Proposal (RC-Onto, for short) ontologies to see if there exists a concept considering those types. I did  not find it. On ifc there is the concept ifc:Building (http://ifcowl.openbimstandards.org/IFC4_ADD2/index.html#http://ifcowl.openbimstandards.org/IFC4_ADD2#IfcBuilding) considered on RC-Onto that contains general characteristics of the Building. How to integrate Building types in the model depends on the information we want to store. May be we can: 
* create a Concept "HIT2GAP:BuildingType" (with Name (op), Description (op), ...other information, PredefinedBuildingSubType (BuildingSubTypeEnum)) to be a superclass of ifc:Building 
* extend  ifc:Building with that information
* Other idea?

b) Regarding Zone, Space, Floor, and Window covering types, Pierre have defined them as enumerates, may be we can:
* Use the ifc:BuildingElement to incorporate those enumerates  (http://ifcowl.openbimstandards.org/IFC4_ADD2/index.html#http://ifcowl.openbimstandards.org/IFC4_ADD2#IfcBuildingElement)
* Create a HIT2GAP:BuildingElements considering those elements (Zone, Space, ....)
* Another idea?
 
c) I also reviewed the APIs related to this information (Section 13.2), I think that depending on what we decide about the data model on this regard, those APIs have to be tuned. I mean, there is information on ifc concepts and in the new concepts that should match with  the APIs. In this point we need to discuss with Pierre.

**Comment by ycardinale** [comment]
Regarding **Section 13.1.2: Geographic Information** (Hemispheres, Climate types, Orientation), there some concepts explicitly considered in the ontology proposed by Richard  (Onto_H2G).

The ifc:SpatialStructuralElement concept hasOrientation, and ifc:Building isA ifc:SpatialStructuralElement. We can integrate Hemispheres and Climate types information related to 
ifc:SpatialStructuralElement.

Also, in Onto_H2G, it is proposed a classification of concepts related to energy equipments (Power System)  into five categories named IGOEE: Identification, Geographical, Operational, Economical, and Ecological.

We can complete the Geographical concepts with (Hemispheres, Climate types, Orientation. Currently only concepts related to Mobility (Location and time) are considered.

In Minerva Ontology there is a GeographicModel, described as "Geographic representation of the entities: This package is focused on linking the SSN module with geographic contextualisation of the information. This ontology will support in the future the geospatial reasoning over the elements of the domain-specific ontologies."

I think that we can extend this Minerva:GeographicModel with this information. 

However, in the APIs,  the Geographic information is attached to the building description, while in Onto_H2G is related partially to ifc:SpatialStructuralElement and to the energy equipments. In Minerva Model ssn:System and ssn:FeatureofInterest inherit from geo_Feature that in turns hasGeometry (GML, WKT). 

Thus, we should see together this subject to decide if it is necessary to create other concepts and relations in Onto_H2G or Minerva Geographic Model. I prefer the first option: Adjust ifc:SpatialStructuralElement.

**Section 13.1.3 Energy categories**. This information was taken from ONTO-MG. Then, it is well considered.

**Section 13.1.4 Systems**. This information was taken from IFC and Haystack. However, there are concepts (Monitoring, Wearable) and relations described in the document D.2.7 that are not described in the document of the Onto_H2G.
We have to take into account these concepts and relations when we work on Building and sensor modeling.

**Section 13.1.5 Measures** This information is from MONDAS?

**Section 13.1.6 Occupancy**. Some of this information is considered on the USER-Simulation Module. However there is other information (such as Distant to a point, Level of Knowledge) that we should discuss how they will be modeled. 

I think that a meeting  to discuss all these aspects is necessary.

**Comment by aolite** [comment]
I have reading D2.7 and Richard's deliverable to construct the model currently available in the following [documentation link](https://hit2gap-eu-project.github.io/HIT2GAPOnt/)

Please revise it and make the corresponding improvements. 

Further dicussion about this topic could continue on issue #23 or #24
